import type { Metadata } from 'next'
import '@fontsource/eb-garamond'
import './globals.css'

export const metadata: Metadata = {
  title: 'Hundred Acre Realm',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
} 