-- CreateTable
CREATE TABLE "Native" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "nativeId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "baseName" TEXT,
    "type" TEXT,
    "group" TEXT,
    "native" TEXT,
    "move" TEXT,
    "lightMoveSpeed" TEXT,
    "lightAttackSpeed" TEXT,
    "lightStrength" TEXT,
    "lightChitColor" TEXT,
    "lightPins" TEXT,
    "darkMoveSpeed" TEXT,
    "darkAttackSpeed" TEXT,
    "darkStrength" TEXT,
    "darkChitColor" TEXT,
    "darkPins" TEXT,
    "warning" TEXT,
    "weight" TEXT,
    "fame" INTEGER,
    "notoriety" INTEGER,
    "gold" INTEGER,
    "treasure" TEXT,
    "containsIds" TEXT,
    "portrait" TEXT,
    "killCount" INTEGER,
    "setupStart" TEXT,
    "containedById" INTEGER,
    "vulnerability" TEXT,
    "armored" INTEGER,
    "sides" TEXT,
    "description" TEXT,
    "strategies" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "Native_nativeId_key" ON "Native"("nativeId");
